/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "main.h"
uint32_t SystemCoreClock = 72000000;

//RTOS HAndles
QueueHandle_t xSensorQueue;
SemaphoreHandle_t xADCMutex;






int main(void)
{
	init_clk();
	init_adc();
	init_switch();
	init_uart1();

	xSensorQueue= xQueueCreate(10,sizeof(sensor_message));
	if(xSensorQueue == NULL)
	{
		while(1);   //failed to create queue

	}

	// creating ADC mutex
	xADCMutex=xSemaphoreCreateMutex();
	if(xADCMutex==NULL)
	{
		while(1);   //Mutex creation failed
	}
	//xTaskCreate(taskfucntion,task name,stack size,fucntion argument,priorites,Task id)

	xTaskCreate(Temperature_task,"TempTask",200,NULL,1,NULL);
	xTaskCreate(Voltage_task,"VoltTask",200,NULL,1,NULL);
	xTaskCreate(Pot_task,"PotTask",200,NULL,1,NULL);
	xTaskCreate(switchtask,"switchTask", 200, NULL, 1, NULL);
	xTaskCreate(UART_task,"UARTTask",200,NULL,2,NULL);

	/*Start schduler*/
	vTaskStartScheduler();
    /* Loop forever */
	for(;;)
	{

	}
}


void vApplicationMallocFailedHook(void)
{
    // Called if pvPortMalloc fails
    while(1); // stop here for debugging
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    // Called on stack overflow
    (void)xTask;
    (void)pcTaskName;
    while(1); // stop here for debugging
}

